INSERT INTO `SUPPLIER_ADMIN`(`Username`, `Password`)
 VALUES ('ccpoe9','12345');

 INSERT INTO `STORES` (`Name`,`Address`,`StoreLogo`,`SupplierAdmin`)
 VALUES ('Walmart', '123 Monroe St','https://logos-world.net/wp-content/uploads/2021/11/Walmart-Logo-700x394.png', 1),
 		('Publix', '188 Marine View Dr','https://logos-world.net/wp-content/uploads/2021/10/Publix-Logo-700x394.png', 1),
 		('Target', '59 Patchogue Ave','https://logos-world.net/wp-content/uploads/2020/10/Target-Logo-700x394.png', 1),
 		('7 Eleven', '14001 Fondren Rd','https://logos-world.net/wp-content/uploads/2021/08/7-Eleven-Logo-700x394.png', 1),
 		('Kroger', '3617 Chandler Ln','https://logos-world.net/wp-content/uploads/2021/09/Kroger-Logo-700x394.png', 1),
        ('Walgreens', '3616 Chandler Ln','https://logos-world.net/wp-content/uploads/2021/11/Walgreens-Logo-700x394.png', 1);

 INSERT INTO `PRODUCTS`(`Name`,`Price`,`ExpireDate`,`Type`, `Description`,`Image`,`StoreID`)
 VALUES ('Jif Peanut Butter, Creamy',3.99,'2023-05-20','Snacks', 'Jif Creamy Peanut Butter is a smooth spread made from roasted peanuts. Its rich and creamy texture is perfect for spreading on bread, crackers, and fruits. With protein, fiber, and healthy fats, it''s a nutritious and delicious snack.', 'https://www.instacart.com/assets/domains/product-image/file/large_fd13505e-f3a0-4ec4-9753-e9458b05a169.jpg', 1),
		('Jif Peanut Butter, Crunchy',3.99,'2023-05-20','Snacks', 'Jif Creamy Peanut Butter is a smooth spread made from roasted peanuts. Its rich and creamy texture is perfect for spreading on bread, crackers, and fruits. With protein, fiber, and healthy fats, it''s a nutritious and delicious snack.', 'https://www.instacart.com/assets/domains/product-image/file/large_fd13505e-f3a0-4ec4-9753-e9458b05a169.jpg', 1),
         ('Tyson Sandwich, Chicken Breast, Spicy',3.49,'2023-05-01','Prepared Food', 'Tyson Spicy Chicken Breast Sandwich is a ready-to-eat meal made with juicy, all-white meat chicken breast and a bold, spicy breading. This crispy and delicious sandwich is perfect for a quick lunch or snack, with a convenient packaging that''s easy to heat and enjoy on the go.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_3a5fe752-a852-48ab-b425-29f171103997.jpeg', 1),
         ('Giovanni Rana Five Cheese Lasagna',5.99,'2023-06-21','Prepared Food', 'Giovanni Rana Five Cheese Lasagna is a mouth-watering Italian classic made with layers of tender lasagna noodles, five creamy cheeses, and a rich tomato sauce. This frozen meal is easy to prepare and perfect for a quick and satisfying dinner.', 'https://www.instacart.com/assets/domains/product-image/file/large_de1fe645-6773-458a-beae-ac1b99834bac.png', 1),
         ('RED BARON Pizza, Classic Crust, Pepperoni', 1.99,'2023-04-29','Prepared Food', 'RED BARON Classic Crust Pepperoni Pizza is a satisfying and flavorful frozen pizza made with zesty tomato sauce, 100% real cheese, and delicious pepperoni.', 'https://www.instacart.com/assets/domains/product-image/file/large_a87ec523-dd07-4e15-90c6-33664da69c99.png', 1),
         ('RED BARON Pizza, Supreme, Brick Oven Crust',1.99,'2023-05-18','Prepared Food', 'RED BARON Brick Oven Crust Supreme Pizza is a delectable frozen pizza that combines savory sausage, peppers, onions, and pepperoni with zesty tomato sauce and 100% real cheese. The brick oven crust bakes up crispy and bubbly, delivering a delicious and satisfying crunch.', 'https://www.instacart.com/assets/domains/product-image/file/large_0215bf83-4306-41fd-acc1-d3d822d3d168.png', 1),
         ('RED BARON Pizza,Original Classic',7.99,'2023-05-18','Prepared Food', 'RED BARON Brick Oven Crust Supreme Pizza is a delectable frozen pizza that combines savory sausage, peppers, onions, and pepperoni with zesty tomato sauce and 100% real cheese. The brick oven crust bakes up crispy and bubbly, delivering a delicious and satisfying crunch.', 'https://www.instacart.com/assets/domains/product-image/file/large_0215bf83-4306-41fd-acc1-d3d822d3d168.png', 1),
         ('Publix Pizza, Self-Rising Crust, Pepperoni',1.99,'2023-04-11','Prepared Food', 'Publix Self-Rising Crust Pepperoni Pizza is a delicious and convenient frozen pizza made with zesty tomato sauce, 100% real cheese, and spicy pepperoni.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_07f42a78-0d7b-4bfd-92b2-ca337e8343dc.JPG', 2),
         ('Ritz Original Flavor Crackers, 1 Box',1.49,'2023-06-11','Snacks', 'Ritz Original Flavor Crackers are a beloved classic that delivers a rich, buttery taste and a satisfying crunch. Made with high-quality ingredients, these crackers are perfect for snacking, entertaining, or pairing with your favorite dips and toppings.', 'https://www.instacart.com/assets/domains/product-image/file/large_a6cc3fdc-f05a-4a29-8923-2767997dbc9f.jpg', 2),
         ('Oreo Chocolate Sandwich Cookies, Family Size',1.49,'2023-06-11','Snacks', 'Oreo Chocolate Sandwich Cookies in Family Size are a classic and irresistible treat that are perfect for sharing. These cookies feature two crisp chocolate wafers with a smooth, creamy filling in between.', 'https://www.instacart.com/assets/domains/product-image/file/large_0c7af67c-215c-4a46-9b3b-5f4ffa3141eb.jpg', 2),
         ('Jif Peanut Butter, Creamy',3.99,'2023-05-05','Snacks', 'Jif Creamy Peanut Butter is a smooth spread made from roasted peanuts. Its rich and creamy texture is perfect for spreading on bread, crackers, and fruits. With protein, fiber, and healthy fats, it''s a nutritious and delicious snack.', 'https://www.instacart.com/assets/domains/product-image/file/large_fd13505e-f3a0-4ec4-9753-e9458b05a169.jpg', 2),
         ('Planters Deluxe Pistachio Mix',5.99,'2023-07-02','Snacks', 'Planters Deluxe Pistachio Mix is a premium blend of roasted and salted pistachios, almonds, and cashews. This nutritious and delicious snack mix is perfect for satisfying cravings and providing an energy boost on the go.', 'https://www.instacart.com/assets/domains/product-image/file/large_b6f1f07a-3225-4679-8703-61e239aee092.jpg', 2),
         ('Steak-umm Steaks, Angus, Sliced',3.99,'2023-08-11','Prepared Food', 'Steak-umm Angus Sliced Steaks are a delicious and high-quality option for a quick and easy meal. Made from 100% pure Angus beef, these thinly sliced steaks cook up in minutes, making them perfect for sandwiches, wraps, and stir-fries.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_949b0640-b84a-4325-a8e1-72008fac3014.jpeg', 3),
         ('RED BARON Pizza, Classic Crust, Pepperoni',1.99,'2023-05-20','Prepared Food', 'RED BARON Classic Crust Pepperoni Pizza is a satisfying and flavorful frozen pizza made with zesty tomato sauce, 100% real cheese, and delicious pepperoni.', 'https://www.instacart.com/assets/domains/product-image/file/large_a87ec523-dd07-4e15-90c6-33664da69c99.png', 3),
         ('DiGiorno Classic Thin Crust Pepperoni',1.99,'2023-05-20','Prepared Food', 'DiGiorno Classic Thin Crust Pepperoni Pizza is a delicious and satisfying frozen pizza made with flavorful tomato sauce, 100% real cheese, and mouth-watering slices of pepperoni.', 'https://www.instacart.com/assets/domains/product-image/file/large_bf04f9d2-fa49-4377-8a82-65facc692dd7.jpg', 3),
         ('Frito-Lay Bold Mix',3.99,'2023-05-05','Snacks', 'Frito-Lay Bold Mix is a tasty assortment of bold and flavorful snacks, including Doritos, Cheetos, and SunChips. With a mix of cheesy, spicy, and crunchy textures, this snack pack offers something for everyone.', 'https://www.instacart.com/assets/domains/product-image/file/large_049a8234-a117-495e-a739-46abb9742de2.png', 3),
         ('Maruchan Ramen Noodle Soup, Chicken Flavor, Souper 6-Pack',0.99,'2023-04-11','Noodles', 'Maruchan Ramen Noodle Soup, Chicken Flavor, Souper 6-Pack is a delicious and satisfying option for a quick and easy meal. This pack contains six individual servings of savory chicken-flavored soup with tender ramen noodles.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_ab480dbd-7274-4c49-b7d1-a5c714b4c775.JPG', 3),
         ('Lay''s Potato Chips, Classic 8 oz',1.99,'2023-04-11','Snacks', 'Lay''s Classic Potato Chips are a timeless snack made with simple ingredients and the perfect amount of salt. These crispy and crunchy chips are made from high-quality potatoes that are sliced thin and cooked to perfection.', 'https://www.instacart.com/assets/domains/product-image/file/large_9df15a3b-0529-43aa-a9e5-b1d069755165.png', 4),
         ('Pepperidge Farm Goldfish Cheddar Crackers 9 Packs',2.99,'2023-06-03','Snacks', 'Pepperidge Farm Goldfish Cheddar Crackers 9 Packs are a delicious and convenient snack made with real cheddar cheese. These fun and playful fish-shaped crackers are perfect for kids and adults alike, and each pack contains a satisfying and crunchy serving size.', 'https://www.instacart.com/assets/domains/product-image/file/large_b1e9424c-d8b8-433e-96a0-466c4ed1c3d9.jpg', 4),
         ('Maruchan Ramen Noodle Soup, Beef Flavor 6-Pack', 0.99,'2023-06-03','Noodles', 'Maruchan Ramen Noodle Soup in Beef Flavor is a quick and easy meal that''s perfect for any time of day. This 6-pack of soup cups comes with everything you need to enjoy a savory and delicious ramen noodle soup in minutes.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_03d6260a-a116-4309-824a-f85e737b66e4.JPG', 4),
         ('Maruchan Ramen Noodle Soup, Oriental Flavor, Souper 6-Pack',0.99,'2023-06-03','Noodles', 'Maruchan Ramen Noodle Soup in Oriental Flavor is a classic, budget-friendly meal option that''s perfect for anyone looking for a quick and easy lunch or snack. This Souper 6-Pack provides six servings of delicious and satisfying ramen noodles with a savory Oriental flavor.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_bae7f312-c2f0-44b7-a1d1-e3a36f7b94cb.JPG', 4),
         ('Maruchan Ramen Noodle Soup, Chicken Flavor, Souper 6-Pack',0.99,'2023-06-03','Noodles', 'Maruchan Ramen Noodle Soup, Chicken Flavor, Souper 6-Pack is a delicious and satisfying option for a quick and easy meal. This pack contains six individual servings of savory chicken-flavored soup with tender ramen noodles.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_ab480dbd-7274-4c49-b7d1-a5c714b4c775.JPG', 4),
         ('Lunchables Lunch Combinations, Turkey and American Cracker Stackers, Fun Pack',1.49,'2023-04-15','Prepared Food', 'This Lunchables is a tasty and convenient lunch option that''s perfect for kids and adults alike. Each pack includes tender turkey slices, mild American cheese, and buttery crackers for a satisfying and delicious meal.', 'https://www.instacart.com/assets/domains/product-image/file/large_6e018395-fa3d-41fa-abd0-4f3f387ca96f.jpg', 5),
         ('Panera Bread Baked Potato Soup Cup',2.99,'2023-04-15','Prepared Food', 'This Panera soup is a rich and creamy soup made with tender chunks of potato, smoky bacon, and flavorful cheese. This soup is a comfort food classic that''s perfect for a warm and satisfying meal on-the-go.', 'https://www.instacart.com/assets/domains/product-image/file/large_888015d2-3370-4eab-a675-6cdc7bdf6efe.png', 5),
         ('Maruchan Ramen Noodle Soup, Chicken Flavor 12-Pack',1.99,'2023-05-12','Noodles', 'Each of this Maruchan pack contains flavorful chicken seasoning and tender noodles that cook up in just a few minutes. With 12 individual servings, this pack is perfect for stocking up your pantry or for taking to work or school.', 'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_9da4f94a-837e-4850-b21e-e6d9120e736f.jpeg', 5),
         ('Lunchables Ham & Swiss Cheese with Crackers Kids Lunch Snack Kit',1.49,'2023-05-12','Prepared Food', 'This Lunchables is a fun and delicious meal option for kids on the go. The kit includes lean ham, Swiss cheese, and crackers, making it a tasty and balanced snack that''s perfect for lunchtime or any time of day.', 'https://www.instacart.com/assets/domains/product-image/file/large_96849b77-fe90-4162-81f8-ede5eccd29b9.jpg', 5),
         ('Ruffles Original Party Size Potato Chips 13 oz',2.49,'2023-05-12','Snacks', 'Ruffles Original Potato Chips are a classic and delicious snack made with crispy, ridged potato chips that have a satisfying crunch. With their bold and flavorful taste, these chips are perfect for sharing with friends and family at parties, picnics, or anytime snacking.', 'https://www.instacart.com/assets/domains/product-image/file/large_b5b7448c-c020-4bff-9745-55e276e26033.png', 5);